name = "Triangle"
uuid = "56f361f5-126b-55db-87fb-1c71988fcde4"
keywords = ["triangle", "triangulation", "delaunay-triangulation", "delaunay-refinement", "delaunay", "voronoi", "constrained-delaunay-triangulation"]
license = "MIT"
desc = "A Julia interface to Jonathan Richard Shewchuk's Triangle library."
authors = ["Francesco Furiani <francesco@furio.me>"]
version = "0.3.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "â‰¥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
